apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: simple-front
  namespace: flux-system
spec:
  image: ghcr.io/davidhaioum/simple-front
  interval: 1m
  secretRef:
    name: regcred
