apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myshop-stable
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: myshop.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: myshop-stable
            port:
              number: 80
