apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: myshop
  namespace: flux-system
spec:
  image: ghcr.io/davidhaioum/myshop
  interval: 1m
  secretRef:
    name: regcred