apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myshop
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: myshop-canary
      stableService: myshop-stable
      trafficRouting:
        nginx:
          stableIngress: myshop-stable
          additionalIngressAnnotations:
            # Enable the sticky session in the Kubernetes Ingress resource
            nginx.ingress.kubernetes.io/affinity: "cookie"
            # Specify the name of the required cookie (default: INGRESSCOOKIE).
            nginx.ingress.kubernetes.io/session-cookie-name: "returnflow-testing"
            # Specify the time before the cookie expires (in seconds):
            nginx.ingress.kubernetes.io/session-cookie-max-age: "3600" # 1h
      steps:
      - setWeight: 50
      - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: myshop
  template:
    metadata:
      labels:
        app: myshop
    spec:
      containers:
      - name: myshop
        image: ghcr.io/davidhaioum/myshop:1.1.0 # {"$imagepolicy": "myshop:myshop"} 
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
      imagePullSecrets:
      - name: regcred
