apiVersion: apps/v1
kind: Deployment
metadata:
  name: front2
  labels:
    app: front2
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: front2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: front2
    spec:
      containers:
      - name: rollouts-demo
        image: ghcr.io/davidhaioum/front:5.0.5 # {"$imagepolicy": "front2:front"} 
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
      imagePullSecrets:
      - name: regcred
